export const US_STATES = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" }
];

export const MAJOR_US_CITIES = [
  "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", 
  "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville",
  "Fort Worth", "Columbus", "Charlotte", "San Francisco", "Indianapolis", 
  "Seattle", "Denver", "Washington", "Boston", "El Paso", "Nashville", 
  "Detroit", "Oklahoma City", "Portland", "Las Vegas", "Memphis", "Louisville",
  "Baltimore", "Milwaukee", "Albuquerque", "Tucson", "Fresno", "Sacramento",
  "Mesa", "Kansas City", "Atlanta", "Long Beach", "Colorado Springs", "Raleigh",
  "Miami", "Virginia Beach", "Omaha", "Oakland", "Minneapolis", "Tulsa",
  "Arlington", "New Orleans", "Wichita", "Cleveland", "Tampa", "Bakersfield",
  "Aurora", "Honolulu", "Anaheim", "Santa Ana", "Corpus Christi", "Riverside",
  "Lexington", "Henderson", "Stockton", "Saint Paul", "Cincinnati", "St. Louis",
  "Pittsburgh", "Greensboro", "Lincoln", "Anchorage", "Plano", "Orlando",
  "Irvine", "Newark", "Durham", "Chula Vista", "Toledo", "Fort Wayne",
  "St. Petersburg", "Laredo", "Jersey City", "Chandler", "Madison", "Lubbock",
  "Scottsdale", "Reno", "Buffalo", "Gilbert", "Glendale", "North Las Vegas",
  "Winston-Salem", "Chesapeake", "Norfolk", "Fremont", "Garland", "Irving",
  "Hialeah", "Richmond", "Boise", "Spokane", "Baton Rouge"
];